################################################################################
#  Binary Search Run 7: disable 320-321 only                                  #
################################################################################

LDFLAGS = -fast -mp -acc -gpu=managed
FFLAGS = -fast -mp -acc -gpu=managed -Mpreprocess -Mbyteswapio -mcmodel=medium -Minfo=accel -DUSE_GPU -DDISABLE_GPU_320 -DDISABLE_GPU_321 $(EXTRA_FLAGS)

#------------------------------------------------------------------------------#

FC      = mpifort
CC      = nvc

#------------------------------------------------------------------------------#

AR         = ar
ARFLAGS    = vru
CPP        = cpp -E
CPPFLAGS   = -DDIRECT -DIEEE -DASCII -DLEN -DUSE_GPU
AS         = as
RANLIB     = ranlib
